on: push
name: Build the application
jobs:
  build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: "Run Makefile build"
        uses: cedrickring/golang-action/go1.14@1.5.2
        with:
          args: make build
