on: push
name: Build the application
jobs:
  build:
    name: run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: "Run Makefile build"
        uses: cedrickring/golang-action/go1.14@1.5.2
        with:
          args: make build
